### ISSUE TITLE
Issue with order when using regex

### ISSUE THREAD

**Issue by HellPat** [menatwork/geolocationRedirect#5]
If i use regex the SQL `sql ORDER BY url, priority` results in a strange order because its sorted by the regex in die `url` field of the table.

e.g. the first directive with lower==stronger priority is executed behind the others.
![bildschirmfoto 2013-07-04 um 15 55 01](https://f.cloud.github.com/assets/1016798/749639/b409b81e-e4b1-11e2-802f-7762b2d1a602.png)

**Comment by HellPat** [comment]
I think `ORDER BY priority, url` should solve the problem?!

**Comment by stefanheimes** [comment]
I think so too. 
PR ist merged.

Can we close this issue ?

**Comment by HellPat** [comment]
Yes. :-)
