### ISSUE TITLE
Compatibilty Contao 3.5.3

### ISSUE THREAD

**Issue by Nolwennig** [menatwork/geolocationRedirect#9]
Hello,

I would like to know if a compatible Contao 3.5.3 release is planned soon?
If yes, when?
if not, how is it possible to help you set up this release?

Best regards,
Nolwennig

**Comment by davidmaack** [comment]
I´m wondering if there is an error on Conao 3.5.3... haven tested it yet :)

**Comment by Nolwennig** [comment]
For me with `Apache 2.4.4` + `PHP 5.4.16` + `MySQL 5.6.12`, _geolocationRedirect_ on _Contao 3.5.3_ **work**, but in `Extension manager` his _Status_ is _Not approved for Contao 3.5.3_.
